### ISSUE TITLE
Source code not only landscape

### ISSUE THREAD

**Issue by n8crwlr** [annshsingh/FlutterWidgetGuide#2]
I really like this app - thanks :blush: 

But, please, can you make the **source code view** _automatic_ instead of _landscape only_?

:+1:

**Comment by annshsingh** [comment]
Hi @n8crwlr 
I am really glad to know that you like the app 😃 
While developing the app, I found the landscape mode to be a bit comfortable to easily scroll through the code. 
This will be removed in the next update, I'll make it optional as suggested by you 👍 

Edit - The code for this issue has been merged with the master branch. Will be pushed to the PlayStore in next update.
