### ISSUE TITLE
I run the white screen on ios

### ISSUE THREAD

**Issue by weiwanfang** [annshsingh/FlutterWidgetGuide#4]
I run the white screen on ios

**Comment by annshsingh** [comment]
Hey @weiwanfang 
I have already mentioned in the README that I have only developed the application keeping android developers in mind, as I find myself proficient in Native Android Development it is comparatively easy for me to resolve android related issues :)

The app is available for download on Play Store as well.

But, I am sure that you can easily run the app on iOS as well, as I have on iPhone XR emulator (haven't checked on a physical device). If you're facing any issues, feel free to make changes at your end to suit your needs :)

Cheers 👍
